### PR TITLE
Add docker. This will be a part of docker-compose that is in vircadia…

### PR DESCRIPTION
**Pull request by hasbegun**
Add docker support. This is a part of effort in vircadia-domain-server-docker docker-compose.
build script will create a docker image 'metaverse-dashboard' and can be used as a part of
docker-compose.
This commit includes 1. Dockerfile, 2 build and run script for dev 3. other supporting files.

### CODE REVIEW

**Comment by digisomni** [comment]
This looks pretty awesome if it is what I think it is. Is the intent for this to be built with the Domain server?

We've been working on a web client repository (https://github.com/vircadia/vircadia-web/) that combines the functionality of the dashboard (this repo) with a web client to visit worlds with. So, to avoid duplicating dashboard work, we figured that this repository should be replaced with that one eventually once we get the features up to spec.

Do you think this same Docker treatment could be applied there without too much trouble?

**Comment by hasbegun** [comment]
Yes, I don't see much troubles down the future. I am very much new to this, and am figuring out the project. If any trouble happens, I will fix it. ^^
Definitely I will take a look at vircadia-web.

**Comment by digisomni** [comment]
Many thanks for your contributing! Is there a test case for this? If this is meant to also run standalone with this repository, could we perhaps add a note or two to the README on how to start / use it? :)

**Comment by hasbegun** [comment]
Good points! I edited README as well including docker section. (merged to my forked repo master)
docker/docker-build.sh will build the image and run-metavase-dashboard.sh will run the dashboard on the docker container (named metaverse-dashboard) at port 8080.

I have tested and running it with docker-compose that I am working with Robert.

**Pull request closed without merging**
